// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcaxUtErNjaidklapkOFLgqQIkP9uDNcU',
    appId: '1:662838981010:web:7f607f71b4ce57810ed14b',
    messagingSenderId: '662838981010',
    projectId: 'login-poc-7ace8',
    authDomain: 'login-poc-7ace8.firebaseapp.com',
    databaseURL: 'https://login-poc-7ace8-default-rtdb.firebaseio.com',
    storageBucket: 'login-poc-7ace8.appspot.com',
    measurementId: 'G-53JLHWMR6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlmdF4QjvhsGY31zNdNfn5x4aaMndPmCA',
    appId: '1:662838981010:android:a46b8301a895ac420ed14b',
    messagingSenderId: '662838981010',
    projectId: 'login-poc-7ace8',
    databaseURL: 'https://login-poc-7ace8-default-rtdb.firebaseio.com',
    storageBucket: 'login-poc-7ace8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyoRp-3MOXP0PEJqYfC7FnlrQ3sPMowd8',
    appId: '1:662838981010:ios:cb1b0adc78913f740ed14b',
    messagingSenderId: '662838981010',
    projectId: 'login-poc-7ace8',
    databaseURL: 'https://login-poc-7ace8-default-rtdb.firebaseio.com',
    storageBucket: 'login-poc-7ace8.appspot.com',
    iosClientId: '662838981010-gr20mf1rti0r85epplr8nbj3t16qrem2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyoRp-3MOXP0PEJqYfC7FnlrQ3sPMowd8',
    appId: '1:662838981010:ios:cb1b0adc78913f740ed14b',
    messagingSenderId: '662838981010',
    projectId: 'login-poc-7ace8',
    databaseURL: 'https://login-poc-7ace8-default-rtdb.firebaseio.com',
    storageBucket: 'login-poc-7ace8.appspot.com',
    iosClientId: '662838981010-gr20mf1rti0r85epplr8nbj3t16qrem2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPoc',
  );
}
